version: "3.8"

name: emitto
services:
  postgres:
    image: postgres:latest

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - critique-postgres-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest

    ports:
      - 6379:6379
    volumes:
      - valkey_data:/usr/local/etc/valkey

  kafka:
    image: apache/kafka:latest

    ports:
      - 9092:9092

volumes:
  critique-postgres-data:
