version: "3.8"

name: ezysend
services:
  postgres:
    image: postgres:latest

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - critique-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

    ports:
      - 6379:6379

  kafka:
    image: apache/kafka:latest

    ports:
      - 9092:9092

volumes:
  critique-postgres-data:
